# PROD docker compose script

services:
  hop-service:
    build: .
    container_name: hop-service
    ports:
      - "5000:5000"
    volumes:
      # Mount SQLite file into container at /data/db.sqlite
      - sqlite-data:/data
    environment:
      DB_URL: "jdbc:sqlite:/data/db.sqlite"
      # NOTE: Will be added on Coolify as env variable
      #API_KEY: "ed5b50b4-a8ef-43d6-8622-9f67f35700e5"

volumes:
  sqlite-data:
