# PROD docker compose script

services:
  hop-service:
    build: .
    container_name: hop-service
    ports:
      - "5000:5000"
    volumes:
      # Mount SQLite file into container at /data/db.sqlite
      - "./app-data:/data"
    environment:
      DB_URL: "jdbc:sqlite:/data/hop-db.sqlite"

