# PROD docker compose script

services:
  hop-service:
    build: .
    container_name: hop-service
    ports:
      - "5000:5000"
    volumes:
      # Mount SQLite file into container at /data/db.sqlite
      - sqlite-data:/data
    environment:
      DB_URL: "jdbc:sqlite:/data/db.sqlite"
      # NOTE: Will be added on Coolify as env variable
      API_KEY: ${API_KEY}
      VALKEY_HOST: "hop-cache"
      VALKEY_PORT: "6379"

  hop-cache:
    image: "valkey/valkey:8-alpine"
    container_name: hop-cache
    ports:
      - "6379:6379"
    command: |
      valkey-server --save "" 
          --appendonly no
          --maxmemory 256mb 
          --maxmemory-policy allkeys-lru

volumes:
  sqlite-data:
